### ISSUE TITLE
Bottom of text is cut off on Chrome tabs

### ISSUE THREAD

**Issue by julianclarke** [supermarin/YosemiteSanFranciscoFont#5]

**Comment by armno** [comment]
confirmed.

<img width="399" alt="screen shot 2558-07-11 at 7 20 20 pm" src="https://cloud.githubusercontent.com/assets/911894/8633721/ee3b170e-2801-11e5-9b1f-feacf1c0e18d.png">

**Comment by FezVrasta** [comment]
https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=511315

**Comment by supermarin** [comment]
It's a known baseline problem, El Capitan fixes it
